name: animated_fab
description: "An Animated Floating Action Button (FAB) for Flutter that expands to reveal a list of sub-FABs with a beautiful animation."
version: 0.0.1
homepage: ""

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:


